//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_65130650.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatPhong()
        {
            this.DichVuDatPhongs = new HashSet<DichVuDatPhong>();
            this.ThanhToans = new HashSet<ThanhToan>();
        }
    
        public string maDatPhong { get; set; }
        public string maKhachHang { get; set; }
        public string maPhong { get; set; }
        public System.DateTime ngayNhanPhong { get; set; }
        public System.DateTime ngayTraPhong { get; set; }
        public int soKhach { get; set; }
        public decimal tienPhong { get; set; }
        public Nullable<decimal> tienDatCoc { get; set; }
        public string trangThaiDatPhong { get; set; }
        public string yeuCauDacBiet { get; set; }
        public Nullable<System.DateTime> ngayDat { get; set; }
        public string nguoiTao { get; set; }
        public Nullable<System.DateTime> ngayCapNhat { get; set; }
        public string lyDoHuy { get; set; }
        public Nullable<System.DateTime> ngayHuy { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual Phong Phong { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DichVuDatPhong> DichVuDatPhongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhToan> ThanhToans { get; set; }
    }
}
