//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_65130650.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVuDatPhong
    {
        public string maDichVuDatPhong { get; set; }
        public string maDatPhong { get; set; }
        public string maDichVu { get; set; }
        public Nullable<int> soLuong { get; set; }
        public decimal donGia { get; set; }
        public decimal thanhTien { get; set; }
        public Nullable<System.DateTime> ngaySuDung { get; set; }
        public string ghiChu { get; set; }
    
        public virtual DatPhong DatPhong { get; set; }
        public virtual DichVu DichVu { get; set; }
    }
}
