//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_65130650.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DichVu()
        {
            this.DichVuDatPhongs = new HashSet<DichVuDatPhong>();
        }
    
        public string maDichVu { get; set; }
        public string tenDichVu { get; set; }
        public string moTa { get; set; }
        public decimal giaDichVu { get; set; }
        public string loaiDichVu { get; set; }
        public Nullable<bool> trangThaiHoatDong { get; set; }
        public string hinhAnh { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DichVuDatPhong> DichVuDatPhongs { get; set; }
    }
}
