//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_65130650.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiPhong()
        {
            this.Phongs = new HashSet<Phong>();
        }
    
        public string maLoaiPhong { get; set; }
        public string tenLoaiPhong { get; set; }
        public string moTa { get; set; }
        public decimal giaCoBan { get; set; }
        public int soNguoiToiDa { get; set; }
        public string loaiGiuong { get; set; }
        public Nullable<decimal> dienTichPhong { get; set; }
        public string tienNghi { get; set; }
        public string hinhAnh { get; set; }
        public Nullable<bool> trangThaiHoatDong { get; set; }
        public Nullable<System.DateTime> ngayTao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phong> Phongs { get; set; }
    }
}
