//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_65130650.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public string maThanhToan { get; set; }
        public string maDatPhong { get; set; }
        public Nullable<System.DateTime> ngayThanhToan { get; set; }
        public decimal soTien { get; set; }
        public Nullable<decimal> tienPhong { get; set; }
        public Nullable<decimal> tienDichVu { get; set; }
        public Nullable<decimal> giamGia { get; set; }
        public string phuongThucThanhToan { get; set; }
        public string trangThaiThanhToan { get; set; }
        public string maGiaoDich { get; set; }
        public string ghiChu { get; set; }
        public string nguoiXuLy { get; set; }
    
        public virtual DatPhong DatPhong { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
